import DS from 'ember-data';

var Host = DS.Model.extend({
  name: DS.attr('string'),
  hostgroup: DS.attr('string'),
  mac: DS.attr('string'),
  domain: DS.attr('string'),
  subnet: DS.attr('string'),
  operatingsystem: DS.attr('string'),
  environment: DS.attr('string'),
  model: DS.attr('string'),
  location: DS.attr('string'),
  organization: DS.attr('string'),
  cpu: DS.attr('string'),
  memory: DS.attr('string'),
  vendor: DS.attr('string'),
  isSelectedAsHypervisor: DS.attr('boolean'),
  isSelectedAsEngine: DS.attr('boolean')
});

Host.reopenClass({
    FIXTURES: [
       // {
       //    id: 1,
       //    name: 'dhcp-3-100.example.com',
       //    hostgroup: 'RHEV Self Hosted Engine',
       //    mac: 'aa:bb:cc:dd:ee',
       //    domain: 'example.com',
       //    subnet: '10.0.3.100',
       //    operatingsystem: 'Fedora 19',
       //    environment: 'Development',
       //    location: 'Tel Aviv',
       //    organization: 'Default_Organization',
       //    type: 'Host::Managed'
       // },
       // {
       //    id: 2,
       //    name: 'dhcp-3-102.example.com',
       //    hostgroup: 'RHEV Self Hosted Engine',
       //    mac: 'aa:bb:aa:dd:ee',
       //    domain: 'example.com',
       //    subnet: '10.0.3.102',
       //    operatingsystem: 'Fedora 19',
       //    environment: 'Development',
       //    location: 'Tel Aviv',
       //    organization: 'Default_Organization',
       //    type: 'Host::Managed'
       // },
       // {
       //    id: 3,
       //    name: 'dhcp-3-103.example.com',
       //    hostgroup: 'RHEV Host',
       //    mac: 'ee:bb:aa:dd:ee',
       //    domain: 'example.com',
       //    subnet: '10.0.3.103',
       //    operatingsystem: 'Fedora 19',
       //    environment: 'Development',
       //    location: 'Tel Aviv',
       //    organization: 'Default_Organization',
       //    type: 'Host::Managed'
       // },
       // {
       //    id: 4,
       //    name: 'dhcp-3-104.example.com',
       //    hostgroup: 'RHEV Host',
       //    mac: '22:bb:11:dd:aa',
       //    domain: 'example.com',
       //    subnet: '10.0.3.104',
       //    operatingsystem: 'Fedora 19',
       //    environment: 'Development',
       //    location: 'Tel Aviv',
       //    organization: 'Default_Organization',
       //    type: 'Host::Managed'
       // },
       {
          id: 5,
          name: 'dhcp-3-105.example.com',
          hostgroup: null,
          mac: 'aa:33:ab:22:ee',
          domain: 'example.com',
          subnet: '10.0.3.105',
          operatingsystem: 'Fedora 19',
          environment: 'Development',
          location: 'Tel Aviv',
          organization: 'Default_Organization',
          cpu: '4 CPU',
          memory: '8 GB',
          vendor: 'Dell',
          type: 'Host::Discovered',
          isSelectedAsHypervisor: false,
          isSelectedAsEngine: false,
       },
       {
          id: 6,
          name: 'dhcp-3-106.example.com',
          hostgroup: null,
          mac: 'bb:cc:ee:dd:aa',
          domain: 'example.com',
          subnet: '10.0.3.106',
          operatingsystem: 'Fedora 19',
          environment: 'Development',
          location: 'Tel Aviv',
          organization: 'Default_Organization',
          cpu: '4 CPU',
          memory: '8 GB',
          vendor: 'Dell',
          type: 'Host::Discovered',
          isSelectedAsHypervisor: false,
          isSelectedAsEngine: false,
       },
       {
          id: 7,
          name: 'cc:01:0E:16:A3:A3',
          hostgroup: null,
          mac: 'cc:01:0E:16:A3:A3',
          domain: null,
          subnet: null,
          operatingsystem: null,
          environment: null,
          location: null,
          organization: null,
          cpu: '4 CPU',
          memory: '8 GB',
          vendor: 'Dell',
          type: 'Host::Discovered',
          isSelectedAsHypervisor: false,
          isSelectedAsEngine: false,
       },
       {
          id: 8,
          name: 'dd:bb:dd:dd:aaa',
          hostgroup: null,
          mac: 'dd:bb:dd:dd:aaa',
          domain: null,
          subnet: null,
          operatingsystem: null,
          environment: null,
          location: null,
          organization: null,
          cpu: '4 CPU',
          memory: '8 GB',
          vendor: 'Dell',
          type: 'Host::Discovered',
          isSelectedAsHypervisor: false,
          isSelectedAsEngine: false,
       }
  ]
});

export default Host;